### ISSUE TITLE
Add command not displaying correct error message

### ISSUE THREAD

**Issue by seah-minlong** [AY2425S1-CS2103T-T16-3/tp#127]
To replicate, 
* try adding `add n/elephant p/321 e/asdf@gmail.com a/addres`
* The error message is as follows: ``` Invalid command format! 
add: Adds a person to the address book. Parameters: n/NAME p/PHONE e/EMAIL a/ADDRESS [t/TAG]...
Example: add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney```
* No mention that roles need to be inputed

**Comment by zzzlou** [comment]
Noted. This was actually in the initial commit but I forgot to include it when resolving conflicts.
