### ISSUE TITLE
AddToGroup having an unintended interaction after editing fields of person

### ISSUE THREAD

**Issue by seah-minlong** [AY2425S1-CS2103T-T16-3/tp#201]
To recreate (Using the default persons):
1. `createGroup g/NUS m/1 2`
2. `search g/NUS` displays Alex Yeoh and Bernice Yu
3. `edit 1 t/` to edit fields of Alex
4. `search g/NUS` will now only display Bernice Yu
5. Doing `addToGroup g/NUS m/1` where Alex is at index 1
  - The follow message appears: "The following users were added to the group NUS:
The following users were already in the group NUS and will remain in the group, the rest of the users have been added accordingly: 
Alex Yeoh"
6.  `search g/NUS` still only shows Bernice Yu

**Comment by chongsun2002** [comment]
In the first place, editing the fields of a person should not remove them from a group. Shall we:

- Upon editing, add them back to every group they were from.

**Comment by chongsun2002** [comment]
Fixed by commit 9e0c1d4
