### ISSUE TITLE
Add Command accepts invalid phone numbers

### ISSUE THREAD

**Issue by chongsun2002** [AY2425S1-CS2103T-T16-3/tp#224]
New person added: John Doe2; Phone: 1123; Email: john@example.com; Address: john street, block 123, #010-11; Tags: 

If the target group is assumed to be NGOs in Singapore, then phone numbers could be checked, to help the user ensure they do not accidentally enter an invalid phone number (which they then forget about in future). For SG phone numbers, they should fulfill the criteria based in: [Telephone numbers in Singapore](https://en.wikipedia.org/wiki/Telephone_numbers_in_Singapore)

**Comment by voldiemort** [comment]
I think assuming that NGOs might at some point work with international partners is fair enough.

With a quick search, seems like the minimum phone number length worldwide is 4. Currently the code checks that phone numbers are at least 3 digits long. Should we just change that to 4 digits then?

**Comment by chongsun2002** [comment]
3 digits for 999 etc. Think if international partners are ok then this should be fine. I'll just change this to an enhancement.
