### ISSUE TITLE
Deleting when addressbook is long

### ISSUE THREAD

**Issue by chongsun2002** [AY2425S1-CS2103T-T16-3/tp#229]
Deleting and editing by index could be inconvenient when the addressbook is long. It makes the addressbook require too much non-CLI interaction as the user has to scroll to find the index, then delete.

Adding a delete by username would be convenient when the addressbook is long.

**Comment by voldiemort** [comment]
Arguably, the user could easily use the `search` command to find the related user first, then proceed to delete. Though it does take one extra action, it still preserves the CLI basis.
