### ISSUE TITLE
[PE-D][Tester A] Incorrect user guide instruction - createGroup, addToGroup, removeFromGroup

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-3/tp#313]
**Description**
The field 'INDICES' in createGroup, addToGroup, removeFromGroup instructions in user guide are in [square bracket], which is indicated as optional in the note. However, 'INDICES' seems to be mandatory to be executed.

**Expected**
Able to execute 
`createGroup g/blood drive 2024`, 

**Actual**
Error message displayed

**Screenshots**
*Figure 1: Instructions on user guide*
![image.png](https://raw.githubusercontent.com/LynetteLeeSiYing/ped/main/files/b4248a02-6369-4027-8e06-55af67a4a981.png)

*Figure 2: Error message*
![image.png](https://raw.githubusercontent.com/LynetteLeeSiYing/ped/main/files/d6352a8a-5944-4446-8e17-86c6688ebf91.png)

**Note**
Similar issues occurred in addToGroup, removeFromGroup.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: LynetteLeeSiYing/ped#1

**Comment by chongsun2002** [comment]
Oops. Got it.

**Comment by chongsun2002** [comment]
Done locally
