### ISSUE TITLE
[PE-D][Tester C] Screenshot mismatch

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-3/tp#317]
Expected GUI on start:

![image.png](https://raw.githubusercontent.com/Siddardar/ped/main/files/77bc96f8-69ff-46f1-9713-a36e634cb821.png)

Actual GUI on start:

![image.png](https://raw.githubusercontent.com/Siddardar/ped/main/files/e6968fd8-f378-4081-9527-5dca9bfe7070.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Siddardar/ped#1

**Comment by chongsun2002** [comment]
Not sure what is going on here since I haven't touched the GUI. @Justin-Yeo you can decide if this is relevant or just based on his system settings (dark mode, etc.)
