### ISSUE TITLE
[PE-D][Tester E] Partnership End Date: invalid date could have more elaboration

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-3/tp#323]
The year required to be input for the `PARTNERSHIP_END_DATE` states that the date input need to be a valid date, but I was able to create a date that is not valid (more than 1000 years ago). If this is allowed, perhaps there could be more elaboration on what a 'valid date' means. 

Steps to recreate: 
```
edit 4 r/partner ped/1023-03-02
```

![image.png](https://raw.githubusercontent.com/tingxuanp/ped/main/files/ef023802-cf09-47b0-b594-14164a8bdb0b.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: tingxuanp/ped#3

**Comment by chongsun2002** [comment]
Can consider either adding this as a feature enhancement or justifying it altogether - how far back would be ok? What if the partnership has ended already, and the organisation still wants to keep the contact. Food for thought.

**Comment by zzzlou** [comment]
Ok by invalid dates I was referring to smth like 2021-02-29 or 2024-03-33. I think we could state that we allow the users flexibility to add past but existed dates, since this is also what most real-life software has been doing.
