### ISSUE TITLE
[PE-D][Tester B] App allows a contact with more than 8 digits in the phone number to be added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-3/tp#326]
**Description**: The AddressBook app allows users to add unusually long phone numbers for contacts, potentially recording erroneous data.

**Steps to Reproduce**:

1. Open the AddressBook app.
2. Enter a command to add a new contact with a long phone number.

   Example command:
   ```plaintext
   add r/volunteer n/Jill p/9999999999999998765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney h/30

**Expected Result**:
The app rejects the contact information as the phone number is longer than 8 digits as expected for Singapore phone numbers.

**Actual Result**:
The app accepts the contact.

![image.png](https://raw.githubusercontent.com/Runus01/ped/main/files/ea7b3efe-55a0-4b51-9308-32e89d99bc13.png)


<!--session: 1731055275750-295d3d6f-a0c8-4807-9fca-76c1c5787955--><!--Version: Desktop v3.5.4-->

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Runus01/ped#3

**Comment by chongsun2002** [comment]
This guy forgot about international phone numbers lol.

But anyways can consider whether we want to restrict to 15 digits and less. Cause supposedly 15 is the longest.

**Comment by seah-minlong** [comment]
I don't think we need to account for this case specifically? It does seem to be a case of extreme user behaviour. Maybe the enhancement can be to check using a library or something if the phone number is relevant in cases where the user accidently types a extra number? 

What do you think @chongsun2002 

![image](https://github.com/user-attachments/assets/487dcae3-48e6-4230-ad7a-f6f7cd90b263)

**Comment by chongsun2002** [comment]
Oh ok. Let's just state in the UG that we allow phone numbers of any length anyways, because they range from 3 digit emergency numbers to 15 digit international numbers, seems like that would be good.
