### ISSUE TITLE
[PE-D][Tester A] Wrong error message: Edit command 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-3/tp#327]
**Description**
Wrong error message for incorrect prefix

**Steps to reproduce**
execute `edit 1 r/partner pred/2022-12-22`

**Expected**
Error message that is relevant

**Actual**
Error message of invalid roles despite having the valid roles inserted

**Screenshots**
![image.png](https://raw.githubusercontent.com/LynetteLeeSiYing/ped/main/files/1272195e-6560-4e6e-9104-ef27dec9c6d2.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: LynetteLeeSiYing/ped#5

**Comment by chongsun2002** [comment]
This one should be considered a bug @seah-minlong @zzzlou @voldiemort @Justin-Yeo . Thoughts?

**Comment by seah-minlong** [comment]
Not a bug, its cus role is case-sensitive (like most of our commands are). Might need to update the UG instead.

**Comment by seah-minlong** [comment]
Yeah bug
