### ISSUE TITLE
[PE-D][Tester D] The system do not allow to create an empty group

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-3/tp#353]
![截屏2024-11-08 18.00.05.png](https://raw.githubusercontent.com/jhqiu21/ped/main/files/655c1a67-5b7b-4f45-a7d0-5a115cd99e16.png)

As shown in the picture above, trying to create a group without person now will lead to invalid command. However in real life, it will be much common for person create group first before the activity, and the owner try to add the relevant person later when the owner get the person list. Hence, it will be better to make member field optional. In other word, a group can persons or not.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jhqiu21/ped#8

**Comment by chongsun2002** [comment]
Fair point but this is not exactly a bug, it's just the design decision that was made. Should we create an enhancement or what...
