### ISSUE TITLE
[PE-D][Tester B] User stories that are not included in the app are still displayed in the developer guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-3/tp#361]
User stories that are not included in the app could be removed from the developer guide. E.g. As a NGO administrator, I wish to archive contacts who are no longer active so that I can keep the active contact list clean without deleting important data.

This will keep the developer guide updated for all stakeholders.

![image.png](https://raw.githubusercontent.com/Runus01/ped/main/files/cc494f29-421e-4cd5-ba62-44f0f0f045cb.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Runus01/ped#11

**Comment by chongsun2002** [comment]
See #336 and #371 .
