### ISSUE TITLE
[PE-D][Tester C] Unicode characters are not allowed in email

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-3/tp#362]
Input:
`edit 1 e/tñst@gmail.com`

Reasoning:
Unicode characters are allowed in the local part of the email. As such `tñst@gmail.com` is a valid email. As mentioned in issue #224, the NGO might have international partners, and as such international email addresses that may contain special characters found in European languages for example should be allowed.

![image.png](https://raw.githubusercontent.com/Siddardar/ped/main/files/1677a110-a63c-4a92-a953-27c2113e0f5f.png)

Expected Behaviour: 
`edit 1 e/tñst@gmail.com` is a valid command. 

Actual Behaviour:
![image.png](https://raw.githubusercontent.com/Siddardar/ped/main/files/deb21b08-2e29-4d60-8d14-116b0fdf48b4.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Siddardar/ped#13

**Comment by seah-minlong** [comment]
It seems that `tñst@gmail.com` is not a valid **english** email. Maybe we can add that only english emails are supported? 

![image](https://github.com/user-attachments/assets/d78a50ec-51f9-4dad-96f4-12d3a4f23a51)

I do think that this could fall under `response.NotInScope` so Im not sure if we want to prioritise this change too

![image](https://github.com/user-attachments/assets/46c3eb24-12cb-4bfd-8584-3179df67ca2c)
