### ISSUE TITLE
[PE-D][Tester E] Missing Important User Stories from DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-3/tp#371]
Some important user stories are missing from the DG, for example, creating groups (not referring to volunteers/donors/partners but groups like `blood donor`), perhaps those could be added in.

![image.png](https://raw.githubusercontent.com/tingxuanp/ped/main/files/fb349191-f963-4ff1-869e-2eaa9531a0bd.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tingxuanp/ped#13

**Comment by chongsun2002** [comment]
See #336 and #361 as well
