### ISSUE TITLE
[PE-D][Tester D] Inconvenient to remove person from group by the persons's index in contact list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-3/tp#376]
![截屏2024-11-08 20.38.23.png](https://raw.githubusercontent.com/jhqiu21/ped/main/files/cee94122-5467-4758-b960-e944c65c8a30.png)

Note that remove a person from group should input person's index in the contact list instead of person's order in the group, which may be inconvenient for users. when there are a lot of person's in the contact list as they have to go through the list to find the target person's index first, and then remove them from the group.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jhqiu21/ped#12

**Comment by seah-minlong** [comment]
yeah I agree. The added tip should make things clearer
