### ISSUE TITLE
[PE-D][Tester D] DG format improvement

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-3/tp#378]
![截屏2024-11-08 20.55.20.png](https://raw.githubusercontent.com/jhqiu21/ped/main/files/3e9bc1c9-d4e3-471e-9256-c83be64e673a.png)

It will be better to remove the header when exporting pdf file.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jhqiu21/ped#14

**Comment by seah-minlong** [comment]
Will remove when we export in the next one.
